"""
Django settings for django_testing project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a1+r9i#b#pr%shrze75e*zu87b+&en!!0oa*!tmsk&%f&-ik3!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'site_index.apps.SiteIndexConfig',
    'polls.apps.PollsConfig',
    'movies.apps.MoviesConfig',
    'candy_factory.apps.CandyFactoryConfig',
    'blog.apps.BlogConfig',
    'tournament.apps.TournamentConfig',
    'todo_list.apps.TodoListConfig',
    'hypergift.apps.HypergiftConfig',
    'wishlist.apps.WishlistConfig',
    'user_manager.apps.UserManagerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_testing.urls'
LOGIN_REDIRECT_URL = reverse_lazy("site_index:index")
LOGOUT_REDIRECT_URL = reverse_lazy("user_manager:index")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_testing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Israel'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom installed application settings

# -- application: site_index
APPLICATION_URLS = [
    {
        "url": "admin/",
        "description": "Django admin",
    },
    {
        "url": "polls/",
        "description": "Django sample polls application",
    },
    {
        "url": "movies/",
        "description": "HyperSkill sample movies application",
    },
    {
        "url": "candy_factory/",
        "description": "HyperSkill sample candy_factory application",
    },
    {
        "url": "blog/",
        "description": "HyperSkill sample blog application",
    },
    # {
    #     "url": "tournament/",
    #     "description": "HyperSkill sample tournament application",
    # },
    {
        "url": "todo_list/",
        "description": "HyperSkill sample todo_list application",
    },
    {
        "url": "hypergift/",
        "description": "HyperSkill sample hypergift application",
    },
    {
        "url": "user_manager/",
        "description": "HyperSkill sample user management application",
    },
    {
        "url": "wishlist/",
        "description": "HyperSkill sample wishlist application",
    },
]

