# Generated by Django 4.1.6 on 2023-02-10 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the book author.', max_length=64)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter the date of the book authors birth, leave blank if unknown.', null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='Enter the date of the book authors death, leave blank if unknown or if author is still alive.', null=True)),
            ],
            options={
                'ordering': ['name', 'date_of_birth', 'date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the book's title.", max_length=256)),
                ('summary', models.TextField(blank=True, help_text='Enter a short summary of the book,can be left empty.', max_length=1024, null=True)),
                ('ISBN', models.CharField(help_text='Enter the book\'s ISBN.see <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('author', models.ForeignKey(help_text="Choose the book's author.", on_delete=django.db.models.deletion.RESTRICT, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the genre (e.g. fiction, historical, etc..).', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the language (e.g.english, french, etc..).', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique id for the book copy across the whole library.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(help_text="Enter the books copy's imprint (specific release/version info).", max_length=264)),
                ('due_back', models.DateField(blank=True, help_text="Enter the date by which the book should be returned if it's on loan, leave blank if the book is not currently on loan.", null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[('1', 'Available'), ('2', 'On Loan'), ('3', 'Reserved'), ('4', 'Maintenance')], default=4, help_text='Book Availability')),
                ('book', models.ForeignKey(help_text="Choose the book copy's general information entry.", on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
            ],
            options={
                'ordering': ['id', 'book', 'imprint', 'status', 'due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Choose the genres to which the book belongs.', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text="Choose the book's language.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
